# ===================================================================
# CONFIGURACIÓN DEL SERVIDOR
# ===================================================================
server.port=8080

# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS POSTGRESQL
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_lealtad_gco
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACIÓN DE JPA E HIBERNATE
# ===================================================================
# 'update' actualiza el esquema de la base de datos automáticamente
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola para facilitar la depuración
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# CONFIGURACIÓN DEL SERVIDOR DE CORREO (SMTP - GMAIL)
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Reemplaza con un correo real de pruebas
spring.mail.username=hawaslycode@gmail.com
# Utiliza una "Contraseña de Aplicación" generada en tu cuenta de Google (no tu clave real)
spring.mail.password=dswb ttbh ozuh odrw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true